### PR TITLE
First pull request

### PR DESCRIPTION
**Pull request by max-mixbook**
Hey Dan,

I wasn't sure how to submit a PR on an initial commit. So I just made a slight updated in a new branch and sent the PR that way.

Master branch is clean. All the work is in the wip branch. Demo is up on gh-pages

### CODE REVIEW

**Comment by danschultz** [comment]
hey @max-mixbook! close this PR and create a new PR that merges the `showView` branch into the `master` branch.

**Comment by danschultz** [comment]
hey @max-mixbook! i'm not able to see your changes. can you close this PR and create a new PR that merges the `showView` branch into the `master` branch?

**Comment by max-mixbook** [comment]
@danschultz hey, i think i need a quick 15 min session on what a pr should look like, or a how dev process should be structured when working with github.

can i come talk to you today...if you escape from the flashmob room?

**Comment by danschultz** [comment]
Sure, I should have be free most of the day on Tuesday. * fingers crossed *

**Pull request closed without merging**
